[deployment]
deploymentTarget = "autoscale"
build = ["sh", "-c", "npm ci && npm run build"]
run = ["sh", "-c", "npm start"]

[[ports]]
localPort = 5000
externalPort = 80

[env]
NODE_ENV = "production"